### ISSUE TITLE
Support for instances

### ISSUE THREAD

**Issue by virtualrepublic** [le717/LDR-Importer#71] opened 2014-05-03 11:49 UTC
It would be very useful and important if there's an option for creating instances of objects. That means that bricks of the same type (not color) have one master and the rest are instances. This would be a huge difference when loading bigger models. I am not familar with Blender but I think it should support instances.

**Comment by le717** [comment] 2016-02-29 02:51
Closing as semi-duplicate of #43 on grounds of tracker cleanup.

**Closed by le717** 2016-02-29 02:51 UTC
Labels: duplicate
