### ISSUE TITLE
ldr-importer does not import all lego blocks

### ISSUE THREAD

**Issue by karelrosseel** [le717/LDR-Importer#116] opened 2016-01-31 13:51 UTC
I am working with lego mindstorms and have problems with importoring block form LDD.lego.com please can you try this also.. 2 blocks (T and gyrosensor) are not importing in blender.. attached 'onderdelen.ldr'
[problem ldr to blender.zip](https://github.com/le717/LDR-Importer/files/111289/problem.ldr.to.blender.zip)

**Comment by le717** [comment] 2016-02-04 21:06
The majority of your LDD export problems can be resolved by updating the LDraw export table. Download the attached file ([source](http://gallaghersart.com/page/new_ldd_parts_and_the_ldraw.xml/)), go to where ever LDD is installed (often C:\Program Files (x86)\LEGO Digital Designer), copy the ldraw.xml file from the zip and replace the one in program files with it. Open LDD, export, then try importing again.

It's not an exact fix, but it help a lot. If it still will not import, then I am unable to help any further.

**Comment by karelrosseel** [comment] 2016-02-07 08:49
Thanks to help me.. I see after the update dat an extra blok is showing up.. good, but still not the 'gyrosensor' of lego mindstorms.. who can help me? thanks a lot.
![extra](https://cloud.githubusercontent.com/assets/12242364/12871526/138f8ebc-cd80-11e5-8aaf-8da66035c7e6.JPG)
![extra-ldd](https://cloud.githubusercontent.com/assets/12242364/12871527/13919194-cd80-11e5-8fd7-58eb1e7a9336.JPG)

**Comment by CrownedComedian** [comment] 2016-02-08 00:50
It appears LDD won't even try to write that brick to the .ldr file.  I suggest exporting the .ldr file from LDD and then opening it in a LDraw application(I use LDCad) and adding the brick there.  You could also manually add the line of code by opening it in a text editor and relocating the brick in Blender.  Unfortunately, the brick imported as several objects in Blender, so just select all of the subparts and Ctrl + J.
![image](https://cloud.githubusercontent.com/assets/7825233/12876721/eab3de72-cdd3-11e5-887b-fba3920a6561.png)

**Comment by karelrosseel** [comment] 2016-02-08 01:07
hi, thanks to help me.. but I does not work for me for the moment.. what do I wrong? I get only crosses.. (I do not know how to work with code in the texteditor) I downloaded http://www.melkert.net/LDCad/download 
![points-from-ldr-to-ldcad](https://cloud.githubusercontent.com/assets/12242364/12876838/a7425c06-ce08-11e5-94cd-8062cf2c004e.JPG)

**Comment by CrownedComedian** [comment] 2016-02-08 01:24
For a quick and dirty fix, copy this line and paste it into your .ldr file(as see in my previous picture):

1 15 0 22 21 1 0 0 0 1 0 0 0 1 99380.dat

If you're interested, here is a link to LDraw's file format documentation. This line of code will make more sense if you read it:
http://www.ldraw.org/article/218

As for LDCad, go to Prefs -> LDraw and make sure the app is finding you part library and config files correctly.  You can also get some extra help here:
http://www.melkert.net/LDCad/docs/start

**Comment by karelrosseel** [comment] 2016-02-08 09:01
Thanks, I paste your code and it worked.. unless one block is not showing up.. see previous problem (there where 2 blocks with problems) I attached the picture.
-> also I tried to fix the libary of LDcad with the movie https://www.youtube.com/watch?v=9HTlrNFj6bw but still does not work.. what do I wrong? I see only red XYZ-arrows.. strange?
![allmost-ok](https://cloud.githubusercontent.com/assets/12242364/12881533/cfe21ff6-ce4a-11e5-8c11-9daf3079c702.JPG)
![ldcad problem](https://cloud.githubusercontent.com/assets/12242364/12881532/cfe1290c-ce4a-11e5-83b9-ea64059395dc.JPG)

**Comment by karelrosseel** [comment] 2016-02-08 09:13
The extra code does not work for extra blocks because I get a 'report: error' in Blender. How comes? Picture of the problem en the file attached.
Thanks to help me.
[problem+all-sensors-not-showing-up.zip](https://github.com/le717/LDR-Importer/files/121336/problem.all-sensors-not-showing-up.zip)

**Comment by karelrosseel** [comment] 2016-02-08 10:24
The NXT mindstorms does export but not the EV3 mindstorm blocks.. why?
![next-versus-ev3-mindstorm-opens-not-in-blender](https://cloud.githubusercontent.com/assets/12242364/12883156/75885a96-ce56-11e5-9908-1650aedd2d62.jpg)

**Comment by CrownedComedian** [comment] 2016-02-08 14:24
No, I don't know all of the pieces by name because... I don't have to!  Every time you select a brick in LDD & LDCad, the part number is shown(see my previous picture).  You can search and download(and move them to your parts library) LDraw brick numbers from a small "lookup" box here:
http://www.ldraw.org/library/tracker/

My LDD won't export the EV3 brick to .ldr, which is why I suggested to build in LDD, export to .ldr, then re-add missing parts in LDCad.  I'm trying to build less in LDD because of this hassle... and this:
http://brickset.com/article/18789

I downloaded my LDraw parts library from the complete.zip(last download link in the link) from here:
http://www.ldraw.org/parts/latest-parts.html

In my LDCad -> Prefs -> LDraw -> Search (library) paths.. -> Current item properties -> Location = C:\Users\NAME\Downloads\complete\ldraw\   and the Type is set to Official Library.  Move this to be first in the search order, hit Accept, then relaunch LDCad.

The eurobrick link was posted in 2013, and in LDD's extended mode, not Mindstorms mode.

Your problem(#116) is not with the importer, but with LDD's .ldr exporter.  There's nothing this importer script could do because it doesn't even know to look for the EV3 brick in a direct export from LDD. HOWEVER, you can blame issue #11 for your all-sensors-not-showing-up problem!!!

If you are still reading this and are able to fix everything, I'd love to see your renders!

**Comment by le717** [comment] 2016-02-08 17:39
Wow, back up the bus. There are multiple reasons for the issues here. I will explain it all later today.

**Comment by CrownedComedian** [comment] 2016-02-08 18:45
Backs up a bus *

**Comment by karelrosseel** [comment] 2016-02-09 06:46
The bus (car) you can find it in ldd.. http://gallaghersart.com/page/new_ldd_parts_and_the_ldraw.xml/ has all parts also

**Comment by karelrosseel** [comment] 2016-02-10 08:52
Does anyone knows how to export an .step file into blender (with colors)?
- Tip:  because I found on https://grabcad.com/library/tag/ev3 the stone/brick of EV3) but by exporting to .stl of .obj my colors are disappeared.

-  LDD will not be availible anymore.. but what is the best opportunity to build a manual of a lego car?)

**Comment by karelrosseel** [comment] 2016-02-10 19:56
problem exporting EV3 blocks in LDD: found at https://community.lego.com/t5/MINDSTORMS/Help-With-Downloading-Additional-EV3-Blocks/m-p/7499794/highlight/false#M20657

**Comment by CrownedComedian** [comment] 2016-02-11 01:50
Well.................. A while ago I found this tutorial on how to export SUPER realistic models from Mecabrick to Blender:
https://www.youtube.com/watch?v=rCMqcTCfD2c

.................................but... For this importer, I suggest sticking to LDraw, as this issue is kinda getting off topic, sorry.

You don't have to use LDCad, there are other LDraw applications out there.

.............

**Comment by karelrosseel** [comment] 2016-02-11 07:23
Good idea but, MECAbrick only imports files from LDD (.lxf) and than I see the import is also not correct form .lxf to mecabric.. always strange.. I posted 'missing parts' also because there are no 'EV3' bricks in the list. http://www.mecabricks.com/en/forum/topic/50/22
![import-lxf-in-megabricks](https://cloud.githubusercontent.com/assets/12242364/12971215/c6c06a7c-d098-11e5-8125-3eba212b1752.PNG)

**Comment by le717** [comment] 2016-02-12 18:43
OK, listen carefully.

1. LDD having issues exporting is not a concern of the script. The problem is the LDD export table, even the one from Gallagher, _does not_ support all the bricks. If you read the site you'll see it says that out of 3,109 bricks in LDD, only approx. 1,770 are supported. The majority of bricks will not export. That is just the way it is. The only way it can be fixed is to have the files correctly defined in the ldraw.xml and it is a very complicated thing to do, something I am unable to do.

2. The EV3 brick is in LDraw, I did [a render](https://www.flickr.com/photos/le717/11309087226/) of it upon importing it using the script.

3. LDD will still be available but not updated. That's it. You can still use and download it all you want.

4. If the script cannot find a part, I cannot do anything about it. #11 relates to the entire script stopping upon hitting that case, but that's it. I cannot "search" for it or anything. If it cannot be found then that's just how it is. It is not my fault if you get a "sources not found" issue. The script just does what it is told. Further, that part may not actually be in LDraw or it is under a different number and the XML is wrong. The only precaution you can take is to make sure you have the latest version of the LDraw parts library, as they often update it.

5. Anything 3D models/Mecabricks I can't help with. Sorry about that.

Hopefully that answers all your questions.

**Comment by CrownedComedian** [comment] 2016-02-12 19:26
That is kinda what I've been saying, I actually still use LDD more than LDCad because most of the bricks I work with safely export from LDD.

...although, it isn't hard to tell the script to jump to the next line if it can't find the file for #11.

**Comment by le717** [comment] 2016-02-12 19:28
> ...although, it isn't hard to tell the script to jump to the next line if it can't find the file for #11.

One would think this, but the way the original author wrote it makes it impossible to do so. Trust me, many have tried. It's not possible. :(

**Comment by CrownedComedian** [comment] 2016-02-15 16:20
No, it's possible.

**Closed** 2016-03-11 20:39 UTC
