### ISSUE TITLE
1.3.2 doesn't work - back to 1.2.0

### ISSUE THREAD

**Issue by virtualrepublic** [le717/LDR-Importer#126] opened 2016-09-11 16:35 UTC
Hello,

I haven't tested the 1.3.0 and 1.3.1 versions so far but 1.3.2 does not work here. I have a LDR-file of the new Porsche and 1.3.0 takes many hours till I get a broken result. With 1.2.0 it takes around 20 minutes and it looks fine. I will attach files later.

**Comment by le717** [comment] 2016-09-19 11:23
Huh, that is strange. Will you lmeaae

**Comment by le717** [comment] 2016-09-19 11:24
Huh, that is strange. Will you please attach the files so I can maybe look into this?

**Comment by virtualrepublic** [comment] 2016-09-19 11:28
[RB0048_LEGO_Technic_42056_Porsche.zip](https://github.com/le717/LDR-Importer/files/479838/RB0048_LEGO_Technic_42056_Porsche.zip)

**Comment by virtualrepublic** [comment] 2016-09-20 11:11
It would be great to add MPD support,

**Comment by le717** [comment] 2016-10-04 12:05
We have never supported MPD models, and model parsing

**Comment by le717** [comment] 2016-10-04 12:06
We have never supported MPD models, and model parsing has not changed. Closing as duplicate of #7.

**Closed by le717** 2016-10-04 12:06 UTC
