### ISSUE TITLE
No LEGO logo onto the studs

### ISSUE THREAD

**Issue by virtualrepublic** [le717/LDR-Importer#70] opened 2014-04-28 21:12 UTC
The LDRAW models seem to have a texture information for mapping the LEGO logo onto the studs. This UV information should be supported by the importer because it will give us the possibility to use a picture as a bump or displacement map.

**Comment by le717** [comment] 2016-02-29 02:49
Closing this as duplicate of #32 on grounds of tracker cleanup.

**Closed by le717** 2016-02-29 02:49 UTC
Labels: duplicate, enhancement
